CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task TEXT NOT NULL,
    risk BOOLEAN DEFAULT 0
);
ALTER TABLE tasks ADD COLUMN completed BOOLEAN DEFAULT 0;
PRAGMA table_info(tasks);
 
